server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/IndependentLei/springcloud-config.git # 仓库名字
          search-paths:
            - springcloud-config # 搜索目录
      label: master # 分支

      # http://localhost:3344/master/config-dev.yaml
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
