server:
  port: 80


spring:
  application:
    name: cloud-order-serice

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
#      defaultZone: http://localhost:7001/eurela  单机版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  # 集群版
#ribbon:
#  ConnectTimeout:5000 #连接时间
#  ReadTimeout:5000  # 读取数据时间
