server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2022?useSSL=false&requireSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

eureka:
  client:
    # 标识自己要入驻 Eureka Server
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      #      defaultZone: http://localhost:7001/eurela  单机版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  # 集群版


mybatis-plus:
  type-aliases-package: com.example.payment.pojo #别名
  mapper-locations: classpath:mapper/*.xml    #mybatis文件
