server:
  port: 9001
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 101.132.65.76:8848 #配置Nacos的地址

management:
  endpoints:
    web:
      exposure:
        include: "*"
